language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: STACK_API_KEY
  on:
    branch: master

notifications:
  email: false
