language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
script:
    - npm test
deploy:
    provider: heroku
    on:
        branch: master

notifications:
    email: false
