language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
script:
    - npm test:coveralls
deploy:
    provider: heroku
    api_key:
        secure: "YOUR ENCRYPTED API KEY"
    on:
        branch: dev
        condition: $MY_ENV = production

notifications:
    email: false
